### ISSUE TITLE
Giving Emotional Feedback Review Within The Learner

### ISSUE THREAD

**Issue by moussa101** [Youssef-Ashraf2099/Educational-platform#151]
A review cannot be made inside the Learner page outside these emotional states : 

'Admiration', 'Adoration', 'Aesthetic Appreciation', 'Amusement', 'Anger', 'Anxiety', 'Awe', 'Awkwardness', 'Boredom', 'Calmness', 'Confusion', 'Craving', 'Disgust', 'Empathetic Pain', 'Entrancement', 'Excitement', 'Fear', 'Horror', 'Interest', 'Joy', 'Nostalgia', 'Relief', 'Romance', 'Sadness', 'Satisfaction', 'Surprise' 

due to the table query Emotional_Feedback throwing an exception.

Location Ex: /Learners/CreateFeedback?learnerId=1

**Comment by Youssef-Ashraf2099** [comment]
https://localhost:7185/Learners/CreateFeedback?learnerId=1

**Comment by moussa101** [comment]
Yes
